CREATE TABLE DEPARTAMENTO(
    CLAVE_DEPTO NUMBER(1),
    NOMBRE VARCHAR(30),
    PRESUPUESTO NUMBER(5),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CLAVE_DEPTO)
);


CREATE TABLE EMPLEADOS(
    CLAVE_EMPLEADO VARCHAR(5),
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(30),
    CLAVE_DEPTO NUMBER(1),
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (CLAVE_EMPLEADO),
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (CLAVE_DEPTO) REFERENCES DEPARTAMENTO(CLAVE_DEPTO)
);

--CREANDO UNA SECUENCIA

CREATE SEQUENCE SECUENCIACLAVEDEPTO START WITH 1 INCREMENT BY 1 MAXVALUE 999 NOCYCLE;


--RELLENANDO LAS TABLAS

INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO) VALUES(SECUENCIACLAVEDEPTO.NEXTVAL,'PERSONAL',80000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO) VALUES(SECUENCIACLAVEDEPTO.NEXTVAL,'ALMACÉN',70000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO) VALUES(SECUENCIACLAVEDEPTO.NEXTVAL,'CONTABILIDAD',60000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO) VALUES(SECUENCIACLAVEDEPTO.NEXTVAL,'MANUFACTURA',50000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO) VALUES(SECUENCIACLAVEDEPTO.NEXTVAL,'EMPAQUE',30000);


INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP01','Armando','López',2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP02','Tatiana','Vargas',1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP03','LAura','García',3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP04','Juan','Pérez',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP05','Iván','López',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP06','Margarita','Hernández',1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP07','Jesús','Pérez',3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP08','Toño','Flores',2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP09','Juan','López',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO) VALUES('EMP10','José','Hernández',5);

--ARREGLOS EN LOS INSERT

UPDATE EMPLEADOS SET NOMBRE='Laura' WHERE NOMBRE='LAura';
UPDATE DEPARTAMENTO SET NOMBRE='Personal' WHERE NOMBRE='PERSONAL';
UPDATE DEPARTAMENTO SET NOMBRE='Almacén' WHERE NOMBRE='ALMACÉN';
UPDATE DEPARTAMENTO SET NOMBRE='Contabilidad' WHERE NOMBRE='CONTABILIDAD';
UPDATE DEPARTAMENTO SET NOMBRE='Manufactura' WHERE NOMBRE='MANUFACTURA';
UPDATE DEPARTAMENTO SET NOMBRE='Empaque' WHERE NOMBRE='EMPAQUE';

--CONSULTAS

--A. Obtener los nombres y apellidos de los empleados.
SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDOS FROM EMPLEADOS;

--B. Obtener los apellidos de los empleados sin repeticiones.
SELECT DISTINCT(EMPLEADOS.APELLIDOS) FROM EMPLEADOS;

--C. Obtener todos los datos de los empleados que se apellidan ‘López’.
SELECT * FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.APELLIDOS = 'López' AND EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO;

--D. Obtener el nombre, apellidos y nombre de departamento de las mujeres que trabajan en la empresa.

SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDOS, DEPARTAMENTO.NOMBRE AS "DEPARTAMENTO" FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO AND EMPLEADOS.NOMBRE LIKE '%a';

--E. Obtener todos los datos de los empleados que se apellidan ‘López’ y los que se apellidan ‘Pérez’.

SELECT * FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO AND EMPLEADOS.APELLIDOS IN('López','Pérez');

--F. Obtener el nombre y la clave de empleado de los trabajadores que trabajan en el departamento 4

SELECT EMPLEADOS.NOMBRE, EMPLEADOS.CLAVE_EMPLEADO FROM EMPLEADOS WHERE EMPLEADOS.CLAVE_DEPTO = 4;

--G. Obtener el nombre y apellidos de los empleados cuyo apellido comienza con ‘H’.

SELECT EMPLEADOS.NOMBRE,EMPLEADOS.APELLIDOS FROM EMPLEADOS WHERE UPPER(EMPLEADOS.APELLIDOS) LIKE 'H%';      --con el upper cambiamos todos los apellidos a mayus por si acaso

--H. Obtener los datos de los departamentos cuyo presupuesto está entre 50000 y 70000 €.

SELECT DEPARTAMENTO.* FROM DEPARTAMENTO WHERE DEPARTAMENTO.PRESUPUESTO BETWEEN 50000 AND 70000;

--I. Obtener la clave de empleado, nombres y apellidos de los empleados que trabajen en el departamento de contabilidad.

SELECT EMPLEADOS.CLAVE_EMPLEADO,EMPLEADOS.NOMBRE,EMPLEADOS.APELLIDOS FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO AND LOWER(DEPARTAMENTO.NOMBRE) = 'contabilidad';

--J. Obtener el nombre y apellidos, así como el nombre del departamento de cada uno de los empleados que laboran en la empresa.
SELECT EMPLEADOS.NOMBRE AS "NOMBRE EMPLEADO",EMPLEADOS.APELLIDOS,DEPARTAMENTO.NOMBRE AS "NOMBRE DEPARTAMENTO" FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO;

--K. Obtener el salario medio de los empleados que trabajan en la empresa.
SELECT DEPARTAMENTO.PRESUPUESTO/2 AS "SALARIO EMPLEADOS PERSONAL" FROM DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO=1;
SELECT DEPARTAMENTO.PRESUPUESTO/2 AS "SALARIO EMPLEADOS ALMACÉN" FROM DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO=2;
SELECT DEPARTAMENTO.PRESUPUESTO/2 AS "SALARIO EMPLEADOS CONTABILIDAD" FROM DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO=3;
SELECT DEPARTAMENTO.PRESUPUESTO/3 AS "SALARIO EMPLEADOS MANUFACTURA" FROM DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO=4;
SELECT DEPARTAMENTO.PRESUPUESTO/1 AS "SALARIO EMPLEADOS EMPAQUE" FROM DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO=5;


--EXTRA PARA CONTAR NUMERO DE EMPLEADOS POR CADA EMPLEO
SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS,DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO = 1 AND DEPARTAMENTO.CLAVE_DEPTO = EMPLEADOS.CLAVE_DEPTO;
SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS,DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO = 2 AND DEPARTAMENTO.CLAVE_DEPTO = EMPLEADOS.CLAVE_DEPTO;
SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS,DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO = 3 AND DEPARTAMENTO.CLAVE_DEPTO = EMPLEADOS.CLAVE_DEPTO;
SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS,DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO = 4 AND DEPARTAMENTO.CLAVE_DEPTO = EMPLEADOS.CLAVE_DEPTO;
SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS,DEPARTAMENTO WHERE DEPARTAMENTO.CLAVE_DEPTO = 5 AND DEPARTAMENTO.CLAVE_DEPTO = EMPLEADOS.CLAVE_DEPTO;

--NO FUNCIONA ESTE
SELECT SUM(DEPARTAMENTO.PRESUPUESTO)/COUNT (EMPLEADOS.CLAVE_EMPLEADO)FROM DEPARTAMENTO,EMPLEADOS;

SELECT COUNT (EMPLEADOS.CLAVE_EMPLEADO) FROM EMPLEADOS;


--L. Obtener el número de empleados cuyo nombre empiece por ‘J’ y trabajen en el departamento de Manufactura.
SELECT COUNT (EMPLEADOS.NOMBRE) AS "Numero trabajadores nombre empieza J y trabajan en manufactura" FROM EMPLEADOS,DEPARTAMENTO WHERE EMPLEADOS.NOMBRE LIKE 'J%' AND EMPLEADOS.CLAVE_DEPTO = DEPARTAMENTO.CLAVE_DEPTO AND DEPARTAMENTO.NOMBRE = 'Manufactura';

