-- A. Mostrar el Nombre de los Ciclos Formativos que son de GRADO SUPERIOR.

SELECT CICLOFORM.NOMBRE FROM CICLOFORM WHERE TIPO='GRADO SUPERIOR';

--B Mostrar el Nombre, Apellidos y Direccion de los profesores.
SELECT DATOSPERSONALES.NOMBRE, DATOSPERSONALES.APELLIDO1, DATOSPERSONALES.APELLIDO2, DIRECCION FROM DATOSPERSONALES WHERE TIPO = 'PROFESOR';

--C. Mostrar el nombre de los ciclos que tienen número de horas entre 150 y 250.
SELECT CICLOFORM.NOMBRE AS "NOMBRE CICLO",ASIGNATURA.NOMBRE AS "NOMBRE ASIGNATURA" FROM CICLOFORM,ASIGNATURA WHERE CICLOFORM.CODCICLO = ASIGNATURA.CODCICLO_CICLOFORM AND ASIGNATURA.NUMHORAS BETWEEN 150 AND 250;

--D Muestre el nombre y el numCuenta de los profesores.
SELECT DATOSPERSONALES.NOMBRE,PROFESOR.CUENTA FROM DATOSPERSONALES,PROFESOR WHERE DATOSPERSONALES.DNI = PROFESOR.DNI;

--E. Muestra el DNI de los alumnos que están matriculados en la asignatura codAsig=3.
SELECT ALUMNO.DNI FROM ALUMNO,MATRICULA WHERE ALUMNO.DNI = MATRICULA.DNI_ALUMNO AND CODASIG_ASIGNATURA = 3;

--F. Muestra el DNI de los profesores que hablan el idioma inglés, utilizando el codIdioma=30.
SELECT PROFESOR.DNI FROM PROFESOR,IDIOMASPROF WHERE PROFESOR.DNI=IDIOMASPROF.DNI_PROFESOR AND CODIDIOMA_IDIOMA=30;

--G. Muestra el nombre de las asignaturas del profesor con DNI 89621477
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA WHERE DNI_PROFESOR LIKE '89621477%';

--H. Muestra el DNI de ANDREA y LUIS.
SELECT DATOSPERSONALES.DNI FROM DATOSPERSONALES WHERE DATOSPERSONALES.NOMBRE IN('ANDREA','LUIS');

